services:
  meteorite-catcher:
    build:
      context: .
      target: dev
    image: meteorite-catcher:latest
    volumes:
      - .:/src
    networks:
      - my-rtsp-network

networks:
  my-rtsp-network:
    name: my-rtsp-network
    external: true

